# Unterstützungsmöglichkeiten / Funding
# Aktiviere die gewünschten Plattformen, sobald verfügbar.

# github: ["username"]
# ko_fi: username
# open_collective: project-name
# patreon: username
# buy_me_a_coffee: username
# custom: ["https://example.com/donate"]
